Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/ClassAndModuleChildren:
  EnforcedStyle: 'compact'

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'
    - 'spec/rails_helper.rb'

# re-evaluate when Ruby 3.0 is out
Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/StringLiterals:
  Exclude:
    - 'bin/spring'
    - 'config/application.rb'
    - 'config/puma.rb'
    - 'db/schema.rb'

Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'config/initializers/backtrace_silencers.rb'
